# Generated by Django 2.0.4 on 2019-08-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190818_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=100, verbose_name='RG'),
        ),
    ]
