# Generated by Django 2.0.4 on 2019-08-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_posto', models.CharField(max_length=255, verbose_name='Nome do Posto')),
                ('cnes', models.CharField(max_length=255, verbose_name='CNES')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
            ],
        ),
    ]
