# Generated by Django 2.2.3 on 2019-08-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_posto', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
