# Generated by Django 2.2.3 on 2019-08-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
